README.md

Add [Zotfile](https://github.com/jlegewie/zotfile) the famous extension for file management in zotero

Add item: Zotefile

---

README.md

Add item: Zotero DOI Manager

---

README.md

Add Zotero Better BibTeX plugin

---

README.md

Adding new productivity section and the famous [Zotero Better Notes](https://github.com/windingwind/zotero-better-notes) extension

Add productivity section and zotero better notes addon

---

README.md

Add the [zotpress](https://wordpress.org/plugins/zotpress/) extension for wordpress websites to include bibliographies from Zotero

Add zotpress website integration extension

---

README.md

Add zotero-style plugin to the list

---

README.md

Fix the order of categories list of plugins

Fix the order of categories.

---

README.md

Fix the alphabetical order of the content

Fix the content order

---

README.md

Add [Zotmoov](https://github.com/wileyyugioh/zotmoov) extension to the list 

Add Zotmoov extension

---

README.md

Add the [zotxt](https://github.com/egh/zotxt) extension to the productivity list.

Add zotxt plugin

---

README.md

Add - [Zotero-attanger](https://github.com/MuiseDestiny/zotero-attanger) an Attachment Manager for Zotero 

Add Zotero-attanger extension

---

README.md

Add zotodo extension

---

README.md

Rename Table of contents to just Contents
NA

Rename table of contents

---

Contributing.md
README.md

Modify contributing part to follow awesome list guidelines
NA

Modify contributing part 

---

.github/workflows/lint.yml

Add famous Awesome lint as CI using GitHub actions. 
NA

Add Awesome list CI

---

README.md

Fix the awesome lint CI problems 
NA

Fix awesome lint problems

---

README.md

Add zotero-date-from-last-modified extension

---

README.md

Add zotcite and cmp-zotcite

---

README.md

Add inciteful-zotero-plugin

---

_README.md

Add a new extension [zotero-arxiv-workflow](https://github.com/AllanChain/zotero-arxiv-workflow). Which help with with adding and updating papers from arxiv.

Add zotero-arxiv-workflow plugin

---

_README.md

Adding  [Ethereal Style for Zotero](https://github.com/MuiseDestiny/zotero-style) plugin to the list

Add  Ethereal Style for Zotero plugin

---

.github/workflows/test_readme.yml
_README.md
generate_readme.py

After the introduction of #23, the linter will not pass awesome lists requirements. so here I try to fix that

 Ensure awesome-lint compliance

---

_README.md

Add Aria, the AI assistant plugin for zotero
NA

Add Aria plugin

---

generate_readme.py

The flat square render for items not working properly so lets remove it

Fix flat rendering by removing flat square style
